
### ***properties for console*** ###
local.dih.endpoint=10000
request.timeout=20000

### ***properties for services management block*** ###
refresh.cpu.chart.time=7200000

lower.iops.limitation=11000
lower.iops.limitation1=13000
lower.throughput.limitation.mb=600
lower.throughput.limitation1.mb=700
test.button.switch.flag=false
deployment.daemon.port=10002
deploy.path=/var/testing/packages
ftp.username=user
ftp.password=user
snapshot.show.flag=true
csi.show.flag=false
volume.detail.show.flag=false


